kind: "CDN"
version: "1"
data:
  originSelectors:
    rules:
      - name: route-all-customdemo-to-edge-function
        when:
          allOf:
            - reqProperty: domain
              equals: "customdemo.run.place"
            - reqProperty: path
              doesNotMatch: "^/global/en(/.*)?$"
        action:
          type: selectAemOrigin
          originName: edgefunction-my-edge-function
          skipCache: true
