kind: "CDN"
version: "1"
data:
  originSelectors:
    rules:
      - name: route-fonterra-auth-to-edge-function
        when:
          allOf:
            - reqProperty: domain
              equals: "customdemo.run.place"
            - reqProperty: path
              like: "/api/v1/web/fonterra-auth*"
        action:
          type: selectAemOrigin
          originName: edgefunction-secure-api-routing
          skipCache: true
