kind: "CDN"
version: "1"
data:
  originSelectors:
    rules:
      - name: route-all-customdemo-to-edge-function
        when:
          reqProperty: domain
          equals: "customdemo.run.place"
        action:
          type: selectAemOrigin
          originName: edgefunction-my-edge-function
          skipCache: true
